"""Shared error contract for JARVIS MVP."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


class ErrorCategory(str, Enum):
    """Fixed MVP error categories."""

    INPUT_ERROR = "INPUT_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    ANSWER_ERROR = "ANSWER_ERROR"
    CLARIFICATION_BLOCK = "CLARIFICATION_BLOCK"
    CONFIRMATION_BLOCK = "CONFIRMATION_BLOCK"
    EXECUTION_ERROR = "EXECUTION_ERROR"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    CANCELLATION = "CANCELLATION"


class ErrorCode(str, Enum):
    """Fixed MVP error codes."""

    EMPTY_INPUT = "EMPTY_INPUT"
    UNREADABLE_INPUT = "UNREADABLE_INPUT"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    UNKNOWN_INTENT = "UNKNOWN_INTENT"
    MISSING_PARAMETER = "MISSING_PARAMETER"
    TARGET_NOT_FOUND = "TARGET_NOT_FOUND"
    MULTIPLE_MATCHES = "MULTIPLE_MATCHES"
    UNSUPPORTED_TARGET = "UNSUPPORTED_TARGET"
    UNSUPPORTED_ACTION = "UNSUPPORTED_ACTION"
    UNSUPPORTED_QUESTION = "UNSUPPORTED_QUESTION"
    SOURCE_NOT_AVAILABLE = "SOURCE_NOT_AVAILABLE"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"
    MODEL_BACKEND_UNAVAILABLE = "MODEL_BACKEND_UNAVAILABLE"
    ANSWER_NOT_GROUNDED = "ANSWER_NOT_GROUNDED"
    ANSWER_GENERATION_FAILED = "ANSWER_GENERATION_FAILED"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    FOLLOWUP_REFERENCE_UNCLEAR = "FOLLOWUP_REFERENCE_UNCLEAR"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    CONFIRMATION_DENIED = "CONFIRMATION_DENIED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    APP_NOT_RUNNING = "APP_NOT_RUNNING"
    WINDOW_UNAVAILABLE = "WINDOW_UNAVAILABLE"
    APP_UNAVAILABLE = "APP_UNAVAILABLE"
    INVALID_URL = "INVALID_URL"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    STEP_FAILED = "STEP_FAILED"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    BLOCKED_STATE_CORRUPTED = "BLOCKED_STATE_CORRUPTED"
    COMMAND_SCOPE_MISMATCH = "COMMAND_SCOPE_MISMATCH"
    USER_CANCELLED = "USER_CANCELLED"


@dataclass(slots=True)
class JarvisError(Exception):
    """Unified error object used across MVP runtime modules."""

    category: ErrorCategory
    code: ErrorCode
    message: str
    details: dict[str, Any] | None = None
    blocking: bool = False
    terminal: bool = False

    def __post_init__(self) -> None:
        Exception.__init__(self, self.message)
